douyin:
  cookie: FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%7D; passport_csrf_token=6add0051656ae4e9463fb11c84ba7b13;
    passport_csrf_token_default=6add0051656ae4e9463fb11c84ba7b13; strategyABtestKey=%221712504035.402%22;
    volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Afalse%2C%22volume%22%3A0.6%7D;
    GlobalGuideTimes=%221712504089%7C0%22; IsDouyinActive=true; LOGIN_STATUS=1; __security_server_data_status=1;
    _bd_ticket_crypt_cookie=7b992ee4e89b4acfd9f95761c500a9f0; _bd_ticket_crypt_doamin=2;
    bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCRWVwSHp5THlQSlBSdXgrY0JKbmpzbHhNSHFTV0JyMmQwKzR1dW1SVlo1ZzdHd3BNZWo0clpyWlZDd01nTXNqKzBIREswZTlDblJVWjUwQ200NWtDWTg9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoxfQ%3D%3D;
    bd_ticket_guard_client_web_domain=2; n_mh=9-mIeuD4wZnlYrrOvfzG3MuT6aQmCUtmr8FxV8Kl8xY;
    passport_assist_user=Cktg5XEPZBuDZRxyr9OsNiiwgXC_HylwzMDgXTKmOeDbPndY_OuAt2l7w_IRMxn66BxQYFw6bcNavvNInEclBDAeeYzAqrFFzUGJEMEaSgo8F-ef2dS2pRRP7clMU0-KOvhx0mwLhsNbOEnggcmrA5orSyajtktEFED9VcC8Zu1CsN-L5PDie1__d_ZoEM-Fzg0Yia_WVCABIgEDtXLs0w%3D%3D;
    passport_auth_status=8ae6e0c7510551184fca87ec1eba85b4%2C; passport_auth_status_ss=8ae6e0c7510551184fca87ec1eba85b4%2C;
    publish_badge_show_info=%220%2C0%2C0%2C1712504091744%22; sessionid=dbd25dbad45c679b9a00e97eeb6274b5;
    sessionid_ss=dbd25dbad45c679b9a00e97eeb6274b5; sid_guard=dbd25dbad45c679b9a00e97eeb6274b5%7C1712504090%7C5183995%7CThu%2C+06-Jun-2024+15%3A34%3A45+GMT;
    sid_tt=dbd25dbad45c679b9a00e97eeb6274b5; sid_ucp_sso_v1=1.0.0-KDM0ZjMzNDIyZjBkNzYzMmE2MzQ3NzZlYjMzNDhmNGY1YzI2Yjk0OTQKHwi3jLD6ic2IBBCT-sqwBhjvMSAMMP_op6QGOAZA9AcaAmxxIiBkYzIxNjkwNjM3ZWU2ZmEyNjU5YTVkNGZlNDcxMWE5MA;
    sid_ucp_v1=1.0.0-KDYwMWFlY2EzOGRkODJhMTgzMzE5MTUxYjU4M2UwZWUzZWYzOWRmNmUKGwi3jLD6ic2IBBCa-sqwBhjvMSAMOAZA9AdIBBoCbHEiIGRiZDI1ZGJhZDQ1YzY3OWI5YTAwZTk3ZWViNjI3NGI1;
    ssid_ucp_sso_v1=1.0.0-KDM0ZjMzNDIyZjBkNzYzMmE2MzQ3NzZlYjMzNDhmNGY1YzI2Yjk0OTQKHwi3jLD6ic2IBBCT-sqwBhjvMSAMMP_op6QGOAZA9AcaAmxxIiBkYzIxNjkwNjM3ZWU2ZmEyNjU5YTVkNGZlNDcxMWE5MA;
    ssid_ucp_v1=1.0.0-KDYwMWFlY2EzOGRkODJhMTgzMzE5MTUxYjU4M2UwZWUzZWYzOWRmNmUKGwi3jLD6ic2IBBCa-sqwBhjvMSAMOAZA9AdIBBoCbHEiIGRiZDI1ZGJhZDQ1YzY3OWI5YTAwZTk3ZWViNjI3NGI1;
    sso_uid_tt=1643b5f63db26b2bcca7bb8dd53e4752; sso_uid_tt_ss=1643b5f63db26b2bcca7bb8dd53e4752;
    store-region=cn-sh; store-region-src=uid; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A2560%2C%5C%22screen_height%5C%22%3A1440%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A4%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A100%7D%22;
    toutiao_sso_user=dc21690637ee6fa2659a5d4fe4711a90; toutiao_sso_user_ss=dc21690637ee6fa2659a5d4fe4711a90;
    uid_tt=2839b5b971b9380776bae9655e71b6bc; uid_tt_ss=2839b5b971b9380776bae9655e71b6bc;
    home_can_add_dy_2_desktop=%221%22; msToken=Ekvh3vbjLdnsWciL69l7vXn79rxt_aWIGt0s4v_ER0G74j7pmiKt2G-bLdZxZBfsemMns_0lf6BIAqvuGs7q4PIHYo6tVs44Q7sykG-UvVDFx2O1q2AwMykoaIH9eP2u;
    my_rd=2; odin_tt=ec5f809aadd7332d8414dec8dc1b8998551dc362f4b814ac52adf6e2b41be5f4cee32f1666632d355bccc8dbd3e9c696;
    stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A0%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A1%7D%22;
    ttwid=1%7C7AOAhcn2BZJ9cz7h5xzvQCvgNWMdwD_XdythLbJbUSo%7C1712504032%7C3400c755284f7bc0c35b382303f13ea07374d942373b1e9ff8643228b7015b03;
    pwa2=%220%7C0%7C2%7C0%22; __ac_nonce=06612bce000c0cca03084; __ac_signature=_02B4Z6wo00f01dANMAwAAIDAdYPq5IRexUXQLTSAABIT09;
    architecture=amd64; device_web_cpu_core=4; device_web_memory_size=8; tt_scid=c5RbzkkinxMBt9tEAn4SgFuIUw1IEqpZZB2XhwYPOxF79LGkyxLe5IzPcr51xXfff0d4;
    ttcid=958ce47ef5ce48cb9a9ca2e4f248651d23; =douyin.com; csrf_session_id=86390e9f362d07a8fb377be7cb0b2c4f;
    dy_sheight=1440; dy_swidth=2560; xg_device_score=6.979237670192787; passport_fe_beating_status=true
  cover: true
  desc: true
  folderize: true
  interval: all
  lyric: true
  max_connections: 5
  max_counts: 0
  max_retries: 5
  max_tasks: 10
  mode: post
  music: true
  naming: '{create}_{desc}'
  page_counts: 20
  path: /mnt/share/md/md10/Vedio
  timeout: 10
  url: https://v.douyin.com/iYkcV28K/
tiktok:
  cookie: null
  max_connections: 5
  max_counts: 0
  max_retries: 5
  max_tasks: 5
  naming: '{create}_{desc}'
  page_counts: 5
  path: Download
  timeout: 10
